### ISSUE TITLE
Legofit returning spread=inf

### ISSUE THREAD

**Issue by alanrogers** [alanrogers/legofit#14]
Got this via email from Jan Koči: after running the first stage (legofit with --stateOut) of our latest batch of models on a few datasets, I noticed that all outputs now show "spread=inf" for the DiffEv cost function. Do you know why that could be? Should we worry about it?

My full command line looks as follows:
legofit -t 64 -1 -S 5000@10000 -S 1000@100000 -S 1000@1000000 --stateOut a1.state a1.lgo data/data.opf > a1.legofit

I also checked with older topology + data and I got a normal spread value (1.53833e-02), so we can exclude a regression in some recent legofit update.

**Comment by alanrogers** [comment]
I think this reflects the range of twoN (population size) or t (time) values allowed within legofit. These ranges are specified by the variables lo_t, hi_t, lo_twoN, and hi_twoN. In the past, the two "hi" values were set to 1e7. Some users complained that they were consistently getting estimates right at these boundaries, so I set them to DBL_MAX. This solved that problem, but I think it has caused the problem that Jan is encountering.

I have just added two options to legofit, --hi_t and --hi_2N, which allow one to specify the upper bounds on time and 2N parameters. Try setting these to 1e7 or so, and see whether this solves the issue. 

I'll leave this issue open until I learn whether this fixes the problem.

The new code is on the devlp branch but not yet on master.

**Comment by janxkoci** [comment]
Hi Alan, I've made some progress over the weekend, although my issue still persists.

> Do you know why that could be? Should we worry about it?

Just to answer these - yes, I should worry. In your docs I've found that large spread values usually signal some problems with convergence. And indeed, one of the first issues I've noticed were very large values (and highly variable across bootstraps) being estimated for some parameters.

Then I noticed some of the time parameters were _not used_ by the model, and were just a side effect of our automatic graph-to-legofit conversion [function](https://github.com/ulasisik/admixtools/commit/9e0c483baa3317d8d61afb882ee4473516278705). In short, to assure matching time points for admixtures, our function creates new branches for each admixture event on each side of the gene flow, with matching time parameters. But then only one of the time params is used for both admixing populations, while the other param stayed there unused. I've made a patch to the function to remove these unused time parameters from the output.

This patch removed all problematic _time_ parameters, but I still see several size parameters (twoN) with highly unrealistic estimates, including for leaf populations, and the **spread** of the cost function **is still infinite**. Things like population size of the Altai Neanderthal on the order of 2e+16. At the moment I have one size parameter for each population segment in the model. This could probably be reduced, however it shouldn't be a problem on its own - my older topology had the same feature (as it was produced by the same function). But my current models are more complex than the older model, with over 30 population segments (for 7 leaf populations without outgroup).

I will try your devlp branch to see if it helps with the issue, but I suspect the problem is somewhere in the model itself.

**Comment by janxkoci** [comment]
So I tried to set `--hi_2N 1e7`, but I still got spread equal to infinity. The argument helped a little, as now I only have one size parameter estimated at 4.15153e+06.

**Comment by janxkoci** [comment]
Hi Alan, it seems the model was simply over-parametrized. After some testing and manual rewriting of the .lgo file we arrived to runs that no longer show infinite spread of the cost function.

The issue was two-fold: on one hand we had too many parameters due to the automatic conversion, and on the other hand, due to a bug in the function, there were also unused parameters in the produced .lgo file. I will try to work more on the first issue and reduce the number of parameters made by default by the function (I patched the second issue and I wait for upstream to merge it).

But I think it may be worth considering to check for unused free parameters when legofit/legosim starts and throw an error when such parametes are found. Do your think this is reasonable? I guess constrained parameters could complicate this, but if any parameter is not used for segment definition nor to constrain another parameter, it should be removed. You could also ignore such params and print a warning instead of an error, rather then fitting them, which is currently the case.

**Comment by alanrogers** [comment]
Let me look at the code. I'll get back to you.

Alan

**Comment by alanrogers** [comment]
I meant to say "let me look at the legofit code".

**Comment by janxkoci** [comment]
I admit this is a very corner-case issue so maybe you don't need to spend your time on it..

**Comment by alanrogers** [comment]
Sorry to be slow.

I don't see how unused parameters would cause the spread=inf problem,
although I agree that it would be good to flag these. Such flags would
help users find bugs in their input files. I've been poring over the
source code in an effort to figure out how best to implement this
feature. But it hasn't been a priority because I assumed it was not
causing the "spread=inf" problem. My understanding is that this
problem was caused by a model that was overparameterized, not by
unused variables. Is this correct?

If not, I'll give this issue higher priority.

Thanks for the feedback, Alan

**Comment by janxkoci** [comment]
Yes, the main problem was that the model was simply overparametrized. Some of the parameters were also unused, which exacerbated the problem.

But what legofit currently does in presence of unused parameters is probably not ideal:

- accepts the unused params;
- fits them to crazy values, as there are no bounds on these params put by other params (since they are not attached to any other params);
  - by "crazy values" I mean often very large, like 2e+16, and _also_ very variable across bootstraps.

The fitting alone probably wastes some resources, but the resulting fitted values create even bigger problem I think. I think it would be preferable to either throw an error or ignore the unused params, rather than let legofit fit them. But on the other hand, most users probably make the lgo model files by hand and don't have unused params in the first place.

**Comment by alanrogers** [comment]
It doesn't fit unused parameters, but it does give them random initial
values. This doesn't waste any appreciable cpu time, and it doesn't
interfere with the process of fitting the other parameters. The main
benefit of flagging unused values, as I see it, is to help users find bugs.

**Comment by janxkoci** [comment]
I see, so they don't affect `cost` & `spread`?

**Comment by alanrogers** [comment]
No. There should be no effect.

**Comment by janxkoci** [comment]
> It doesn't fit unused parameters, but it does give them random initial values.

One question - why are the initial values random and not taken from the `.lgo` file? I'm asking because my "unused" parameters had specified initial values in the `.lgo` file, the params were just not used in any segment (nor constraints). Are the initial values from `.lgo` files used by legofit?

**Comment by alanrogers** [comment]
The optimization algorithm (differential evolution) maintains a swarm of
points--10 times as many points as there are free parameters. One point in
the initial swarm has values as given by the initial values in the .lgo
file. The rest of the points have random initial values.

The rationale for the non-random point is that it allows the 2nd stage of
analysis to pick up where the 1st stage left off. It also allows the user
to investigate a particular point in parameter space. The rationale for the
random points is that they give the optimizer a better chance of finding
new optima.

**Comment by alanrogers** [comment]
To summarize, legofit allows users to define parameters that are never used, and it doesn't issue any warnings about this. These parameters are not fit by the algorithm, so they shouldn't affect the answers in any way. It would be good to flag these, because they are likely to represent errors in user input, but they don't do any harm. Fixing this would require a lot of work, so I'm not going to make this a priority.
